#!/bin/sh

EXAMPLE_PATH="/usr/share/guadalinex-noodle/"
USERNAME=`whoami`
MULTISYNC="${HOME}/.multisync/"

[ -e $HOME ] || exit 1

[ ! -e ${MULTISYNC} ] &&  mkdir ${MULTISYNC}

[ ! -e "${MULTISYNC}/old" ] && mkdir ${MULTISYNC}/old

[ -e "${MULTISYNC}/1" ] && mv ${MULTISYNC}/1 ${MULTISYNC}/old/1.`date +%Y%m%e_%H%M`

mkdir ${MULTISYNC}/1


if [ ! `pgrep -u $USER vdccm` ]
then
	vdccm
fi
cp ${EXAMPLE_PATH}/vdccm.desktop $HOME/.config/autostart

sed "s#__HOME__#${HOME}#g" ${EXAMPLE_PATH}/localsettings > ${HOME}/.multisync/1/localsettings
cp ${EXAMPLE_PATH}/syncpair ${HOME}/.multisync/1/syncpair

chown -R $USERNAME.$USERNAME $HOME/.multisync

touch $HOME/.psuite

exit 0
