#!/bin/bash

. /lib/partman/definitions.sh

mypart=''
mysize=0

get_some_device_on_dev() {
    if [ "$(grep ${dev//*=/} /proc/partitions | wc -l)" != "1" ]; then
        db_subst partman-auto/text/use_device DEVICE $(device_name $dev)
        db_metaget partman-auto/text/use_device description
        printf "$dev\t$RET\n"
    fi
}

dev="$1"

if [ -z "$dev" ]; then
    for dev in $DEVICES/*; do
	[ -d "$dev" ] || continue
	device="$(cat $dev/device)"
	case $device in
	    /dev/mapper/*-*)
		continue
		;;
	esac
        get_some_device_on_dev
    done
else
    get_some_device_on_dev
fi
