#!/bin/bash

#
# Description:
#   GLIG is a Guadalinex Live Image Generator.
#  
#   This program generate a chroot system from a debian repository in order
#   to create a squashfs compressed image of that system for being able to run
#   as a live GNU/Linux system.
#
# Authors: 
#   Juan Jesús Ojeda Croissier (juanje) <jojeda@emergya.es>   
#
# Last modified: 
#   $Date$ 
#   $Author$
#



revision="$Rev$"
log_file="/var/log/glig-$(date +%Y%m%d%H%M).log"

# Functions
function error() {

    echo "Error: $*" >&2 
    exit

}

function must_be_root() {

    id=$(id -u)
    if [ "$id" != 0 ]; then
        error "You are not a root and you need to be root to run this script"
    fi

}

function log_it() {

    code="$1"
    shift
    msg="$*"
    case $code in
        0)
            echo "${msg} ($(date +'%b %e %H:%M:%S')): OK" | tee -a $log_file
            ;;
        *)
            echo "${msg} ($(date +'%b %e %H:%M:%S')): Fail" | tee -a $log_file >&2
            ;;
    esac
}

function get_config() {

    paths="/etc/glig $HOME/glig ."
    
    any_path=false
    for path in $paths;
        do
        if [ -f "${path}/conf" ]; then
            . ${path}/conf
            any_path=true
        fi
    done
    
    if [ $any_path = false ]; then
        error "There is not any conf file in $paths"
        exit
    fi
    
    escaped_sources=$(echo $sources | sed 's|/|\\/|g')
    log_it "$?" "get_config"

}

function set_config() {

    debootstrap=${_debootstrap:-${debootstrap}}
    squashfs=${_squashfs:-${squashfs}}
    keep_sources=${_keep_sources:-${keep_sources}}
    quiet=${_quiet:-${quiet}}
    verbose=${_verbose:-${verbose}}

    cat <<EOF > $log_file

Configuration values:
  mirror       = $mirror
  components   = $components
  live_dir     = $live_dir
  sources      = $sources
  base         = $base
  live         = $live
  debootstrap  = $debootstrap
  squashfs     = $squashfs
  keep_sources = $keep_sources
  quiet        = $quiet
  verbose      = $verbose

EOF

    log_it "$?" "Setting the config"

}

function apt_get() {

    export LC_ALL=C LANGUAGE=C LANG=C DEBIAN_FRONTEND=noninteractive 
    chroot ${sources} apt-get -f -y --force-yes $*
    log_it "$?" "apt-get -f -y --force-yes $*"

}

function umount_sources() {

    grep -q ${escaped_sources} /proc/mounts && \
    awk "/${escaped_sources}/ {print \$2};" /proc/mounts | sort -r | xargs umount

}

function do_debootstrap() {

    debootstrap --components=${components} \
    --exclude=guadalinex-minimal-conf,ubuntu-desktop,ubuntu-artwork,ubuntu-keyring,ubuntu-minimal,ubuntu-standard edgy ${sources} ${mirror}


    log_it "$?" "do debootstrap"

    # HACK: This is a ugly hack for avoiding the debconf ask to configure 
    # the kernel package
    cat <<EOF > ${sources}/etc/kernel-img.conf
do_symlinks = yes
relative_links = yes
do_bootloader = no
do_bootfloppy = no
do_initrd = yes
link_in_boot = no
EOF

    if [[ $mirror =~ ^file\:\/\/\/ ]]; then
        [ ! -d ${sources}/var/mirror ] && mkdir -p ${sources}/var/mirror
        mount --bind ${mirror#file://} ${sources}/var/mirror
        APT_LINE="deb file:///var/mirror edgy $(echo $components | sed -e 's/,/ /g')"
        echo "$APT_LINE" > ${sources}/etc/apt/sources.list
    fi

    mv ${sources}/sbin/start-stop-daemon ${sources}/sbin/start-stop-daemon.REAL
    echo \
"#!/bin/sh
echo
echo \"Warning: Fake start-stop-daemon called, doing nothing\"" > ${sources}/sbin/start-stop-daemon
    chmod 755 ${sources}/sbin/start-stop-daemon

    # Force update, install and clean
    apt_get update

    # Before continuing, we assure that most recent versions of all pkgs are
    # installed (debootstrap don't assure that)
    apt_get upgrade
    
    apt_get install
    apt_get install linux-image-generic
    
    apt_get install acpi-support

    mkdir -p ${sources}/etc/ssl/private/
    touch ${sources}/etc/ssl/private/ssl-cert-snakeoil.key

    mount --bind /proc ${sources}/proc
    log_it "$?" "mount ${sources}/proc"
    mount --bind /sys ${sources}/sys
    log_it "$?" "mount ${sources}/sys"

    apt_get install guadalinex-minimal-conf
    apt_get install

    apt_get install guadalinex-standard
    apt_get install

    apt_get install guadalinex-standard-conf
    apt_get install
 
    apt_get install anacron
    chroot ${sources} /sbin/start-stop-daemon.REAL --stop --exec /usr/sbin/anacron --oknodo --quiet   

    apt_get install guadalinex-artwork guadalinex-doc casper casper-guada ubiquity-casper-guada ubiquity-frontend-gtk ubiquity-ubuntu-artwork ubiquity-guadalinex-lang xfsprogs jfsutils ntfsprogs discover1 xresprobe laptop-detect libgl1-mesa-glx
    apt_get install

    apt_get install guadalinex-desktop
    apt_get install
    
    apt_get install guadalinex-desktop-conf
    apt_get install

    apt_get install meta-guadalinex-v4
    apt_get install

    apt_get clean

    cat > ${sources}/etc/apt/sources.list <<EOF
deb http://v4.guadalinex.org/ubuntu edgy main restricted universe multiverse
deb http://v4.guadalinex.org/guadalinex-toro toro main restricted universe multiverse
deb http://v4.guadalinex.org/guadalinex-toro toro-updates main restricted universe multiverse
deb http://v4.guadalinex.org/guadalinex-toro toro-security main restricted universe multiverse
deb http://v4.guadalinex.org/guadalinex-toro toro-backports main restricted universe multiverse
EOF

    apt_get update

    # Umount pocfs inside sources, if any
    umount_sources

    # Delete empty mirror directory
    rmdir ${sources}/var/mirror
    log_it "$?" "Delete ${sources}/var/mirror"

    mv ${sources}/sbin/start-stop-daemon.REAL ${sources}/sbin/start-stop-daemon
}

function create_manifests() {

    chroot ${sources} dpkg-query -W --showformat='${Package} ${Version}\n' > ${live_dir}livecd.ubuntu.manifest

    log_it "$?" "create manifest"

    filter="/tmp/filter"
    if [ -f "$filter" ]; then
        rm -f $filter
    fi
    for i in $(echo $live | tr ',' ' ' );
        do
        echo "/$i/d" >> $filter
    done
    
    sed -f $filter < ${live_dir}livecd.ubuntu.manifest > ${live_dir}livecd.ubuntu.manifest-desktop 

    log_it "$?" "create manifest-desktop"

    rm -f $filter
}

function create_squashfs() {
    
    if [ -f "${live_dir}livecd.ubuntu.squashfs" ]; then
        rm -f ${live_dir}livecd.ubuntu.squashfs
    fi
    mksquashfs ${sources} ${live_dir}livecd.ubuntu.squashfs

    log_it "$?" "create squashfs"

}

function copy_files() {

    if [ -f "${live_dir}livecd.ubuntu.initrd-generic" ]; then
        rm -f ${live_dir}livecd.ubuntu.initrd-generic
    fi
    initrd=$(readlink ${sources}initrd.img)
    test -f "${sources}${initrd}" || error "${sources}initrd.img not found"
    cp ${sources}${initrd} ${live_dir}livecd.ubuntu.initrd-generic 
    log_it "$?" "copy initrd"

    if [ -f "${live_dir}livecd.ubuntu.kernel-generic" ]; then
    	rm -f ${live_dir}livecd.ubuntu.kernel-generic
    fi
    kernel=$(readlink ${sources}vmlinuz)
    test -f "${sources}${kernel}" || error "${sources}vmlinuz not found"
    cp ${sources}${kernel} ${live_dir}livecd.ubuntu.kernel-generic 
    log_it "$?" "copy kernel"

}

function set_perms() {

    chmod 666 ${live_dir}/*

}

function usage() {

    program=$(basename $0)
    cat <<EOF
Usage:
    $program [-h] [-d | --no-deboostrap] [-s | --no-squashfs] [-k | --keep-sources] \
[-q | --quiet] [-v | --verbose]

Options:
    -h, --help             Show this help
    -d, --no-debootstrap   Not to build from the packages
    -s, --no-squashfs      Not to create the squashfs image
    -k, --keep-sources     Keep the sources directory after finish
    -q, --quiet            Don't show any messages
    -v, --verbose          Show more information about the execution

EOF

}

######## Here starts the script ########

while [ "$#" -gt 0 ]
do
    case $1 in
        -h|--help) 
                usage
                exit 0
                ;;
        -d|--no-debootstrap)
                _debootstrap="no"
                shift
                ;;
        -s|--no-squashfs) 
                _squashfs="no"
                shift
                ;;
        -k|--keep-sources) 
                _keep_sources="yes"
                shift
                ;;
        -q|--quiet)  
                _quiet="yes"
                shift
                ;;
        -v|--verbose) 
                _verbose="yes"
                shift
                ;;
        *) 
                usage
                exit 0
                ;;
    esac
done

must_be_root

get_config

set_config

if [ "$quiet" = "yes" ]; then
    exec &> $log_file
fi

if [ "$verbose" = "yes" ]; then
    set -x
fi

if [ "$debootstrap" = "yes" ]; then
    do_debootstrap
fi

create_manifests

if [ "$squashfs" = "yes" ]; then
    create_squashfs
fi

copy_files

set_perms

if [ "$keep_sources" != "yes" ]; then
    rm -fr ${sources}
fi

echo "Live system is ready to build!"

# vim:ai:et:sts=4:tw=80:sw=4:
