#!/bin/bash

CONFFILE="/usr/share/g3g/soportados"
CONT=0
SELECTED="${HOME}/.g3g"
USERGROUPS="`id -nG | xargs`"

if [[ "$USERGROUPS" =~ "admin" ]] && [[ ! $USERGROUPS =~ "dialout" ]];then
   gksudo -m "Es necesario que usted pertenezca al grupo \"dialout\", introduzca la clave del administrador para añadir a su usuario sino no podrá conectarse a internet con su dispositivo 3G" adduser $USERNAME dialout 
   zenity --height=300 --info --text "Se ha añadido correctamente su usuario al grupo 'dialout'. Deberá volver a iniciar sesión en su escritorio para que los cambios surtan efecto"
   exit 0
elif [[ ! "$USERGROUPS" =~ "admin" ]] && [[ ! $USERGROUPS =~ "dialout" ]]; then
   zenity --height=300 --info --text "Debe contactar con el administrador del sistema para que le añada al grupo 'dialout'"
   exit 1
fi
   

if [ -f "$CONFFILE" ]; then
    for a in `awk {'print $1'} $CONFFILE`;do
        OPERATORS[$CONT]="FALSE $a"
        CONT=$(expr ${CONT} + 1)
    done
else
    echo "No existe el fichero \"soportados\" en /usr/share/g3g"
    exit 1
fi

if [ -e "$SELECTED" ]; then
   SEL=`cat $SELECTED`
   for i in `seq 0 ${#OPERATORS[@]}`;do
       if [ "${OPERATORS[$i]}" = "FALSE $SEL" ];then
          OPERATORS[$i]="TRUE ${OPERATORS[$i]#FALSE}"
       fi
   done
fi

SELECTION=`zenity --height=300 --window-icon=/usr/share/pixmaps/g3g.png --list --radiolist --title="Asistente para conexión 3G" --text="Actualmente existe soporte en Guadalinex para los siguientes operadores.\n Seleccione el suyo para lanzar el programa apropiado" --column="" --column="OPERATORS" ${OPERATORS[@]}`

if [ -z "$SELECTION" ];then
    exit 1
else
    echo $SELECTION > ~/.g3g
    COMMAND=`grep $SELECTION $CONFFILE|cut -f2`
    exec $COMMAND
fi
