#!/bin/sh

set -e

test -f /bin/setupcon || exit 0

. /lib/lsb/init-functions

case "$1" in
    stop)
        # keyboard-setup isn't a daemon
        ;;
    start|force-reload|restart|reload)
	if [ -z "$DISPLAY" ]; then
	    log_begin_msg "Setting preliminary keymap..."
	    if setupcon -k --force; then
		log_end_msg 0
	    else
		log_end_msg $?
	    fi
	fi
	;;
    *)
        echo 'Usage: /etc/init.d/keyboard-setup {start|reload|restart|force-reload|stop}'
        exit 1
        ;;
esac

