#!/bin/bash

# Creamos directorio temporal para almacenar algunos ficheros que se deben mantener
mkdir /var/tmp

if [ -e "/usr/share/applications/ipodder.desktop" ];then
   mv /usr/share/applications/ipodder.desktop /var/tmp/
fi

# Eliminamos los esquemas de gconf y el paquete xscreensaver que dan problemas al actualizar
rm -rf /etc/gconf/gconf.xml.defaults/* /etc/gconf/schemas

# Si existe un .gconf/apps/panel lo eliminamos pues entra en conficto con el nuevo panel de gv4,
# el usuario pierde los applets que tuviera

for h in `ls /home`;do
    if [ -d /home/$h/.gconf/apps/panel ];then
        rm -rf /home/$h/.gconf/apps/panel
    fi
done

apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf install dpkg >> /tmp/simulate.log 2>&1 
dpkg --configure -a >> /tmp/simulate.log 2>&1

# Fake para que no levante servicios en la simulacion
if [ ! -e /sbin/start-stop-daemon.REAL ];then
   mv /sbin/start-stop-daemon /sbin/start-stop-daemon.REAL
   cat > /sbin/start-stop-daemon <<EOF
#!/bin/bash
echo "Estas usando un fake de este script, el original es start-stop-daemon.REAL"
exit 0
EOF
   chmod +x /sbin/start-stop-daemon
fi

apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf remove xscreensaver >> /tmp/simulate.log 2>&1
apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf dist-upgrade >> /tmp/simulate.log 2>&1
dpkg --configure -a >> /tmp/simulate.log 2>&1

# Eliminamos los metapaquetes de v3
apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf remove guadalinex-v3* >> /tmp/simulate.log 2>&1

# Instalamos paquetes necesarios y los metapaquetes de v4
apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf install openoffice.org openoffice.org-evolution openoffice.org-gnome >> /tmp/simulate.log 2>&1
apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf install meta-guadalinex-v4 xserver-xorg-video-all >> /tmp/simulate.log 2>&1
apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf -f install >> /tmp/simulate.log 2>&1
dpkg --configure -a >> /tmp/simulate.log 2>&1
touch /tmp/goutupgrade
