#!/bin/bash

# Comienza la simulacion
DEBIAN_FRONTEND=noninteractive chroot /tmp/simulate apt-get --config-file /usr/share/guadalinex-upgrader/gu.apt.conf dist-upgrade 2> /tmp/errors

# Comprobamos si todo ha salido bien
if [ "$?" != "0" ];then
   echo "1" > /tmp/guadalinex-upgrader.exit
   zenity --window-icon=/usr/share/pixmaps/guadalinex-upgrader.png --error --text "Lo sentimos, no es posible llevar a cabo la actualización, se ha encontrado el siguiente problema:
$(cat /tmp/errors|grep error)"
   killall apt-get
else
   mv /tmp/rw/var/cache/apt/archives/*.deb /var/cache/apt/archives/
   echo "0" > /tmp/guadalinex-upgrader.exit
fi

# Desmontamos
awk "/\/tmp\/simulate/ {print \$2}" /proc/mounts | sort -r|xargs umount

# Restauramos start-stop-daemon
mv /sbin/start-stop-daemon.REAL /sbin/start-stop-daemon
touch /tmp/gout
